# Generated by Django 6.1 on 2026-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_announcement_alter_auction_status_item_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_items/'),
        ),
    ]
